### ISSUE TITLE
https://drewnoakes.com/fix-decoder/ is not working

### ISSUE THREAD

**Issue by A-World** [drewnoakes/fix-decoder#37]
https://drewnoakes.com/fix-decoder/ is not working. Can you please check?

**Comment by krasnyt** [comment]
+1 
I don't want to switch to a different tool.

**Comment by matiev-ruslan** [comment]
+1

**Comment by drewnoakes** [comment]
Apologies folks. AWS killed my server and I'll have to spend some time setting it back up again. I'll get to it asap.

**Comment by A-World** [comment]
Any plan to bring it up? It is still down.

**Comment by drewnoakes** [comment]
Thanks for your patience. It should be back online now.

**Comment by krasnyt** [comment]
Hi Drew, it seems it's down again :-(

**Comment by drewnoakes** [comment]
@krasnyt could you try it again now please? AWS stopped my instance again. I believe it's back up now.

**Comment by krasnyt** [comment]
Yes, thanks!

**Comment by krasnyt** [comment]
Hi there, me again, looks like it's down 😢
